apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  rmqhost: {{ .Values.RMQ.host }}
  rmqport: {{ .Values.RMQ.port }}
  rmqpass: {{ .Values.RMQ.password }}
  rmquser: {{ .Values.RMQ.user }}
  mysqlhost: {{ .Values.MYSQL.host }}
  mysqlpassword: {{ .Values.MYSQL.password }}
  mysqluser: {{ .Values.MYSQL.user }}
  mysqldatabase: {{ .Values.MYSQL.database }}